### ISSUE TITLE
latest ortools breaks populationsim so we froze the required package version 

### ISSUE THREAD

**Issue by bstabler** [ActivitySim/populationsim#108]
@binnympaul "Looks like the new release of ortools (7.5.7466, released Jan 28) is breaking populationsim. I’m trying a run after installing the previous version of ortools (7.4.7247 )and PopulationSim seems to be running beyond the error point."

**Comment by bstabler** [comment]
For the time being, after running `pip install populationsim`, run the following command:

`pip install ortools==7.4.7247`

**Comment by blakerosenthal** [comment]
This seems to be related to https://github.com/google/or-tools/issues/1874

The latest version of ortools has some uncompiled binaries that require the [VS C++ redistributable](https://visualstudio.microsoft.com/downloads/?q=Redistributable) extra be installed on Windows 10.

**Comment by fpnick** [comment]
Is this going to be the case for all the following versions? In my case, I don' think I could ship my code with this additional requirement.

**Comment by blakerosenthal** [comment]
> Is this going to be the case for all the following versions? In my case, I don' think I could ship my code with this additional requirement.

@fpnick I think you meant to comment on https://github.com/google/or-tools/issues/1874! [PopulationSim](https://github.com/ActivitySim/populationsim) would prefer not to ship with this requirement either! 😅

**Comment by fpnick** [comment]
No, I did mean to comment here, I thought you knew more details about this :D 

My issue over there was closed, so I don't have big hopes that they'll get rid of that again...

**Comment by blakerosenthal** [comment]
@fpnick Hoping they include all the precompiled stuff in future releases! Looks like the documentation has been [updated](https://github.com/google/or-tools/issues/1872) to include the VS C++ installation though, so there's a possibility they'll leave this dependency around for a while :/
