### ISSUE TITLE
Standard license

### ISSUE THREAD

**Issue by josiekre** [ActivitySim/populationsim#115]
We are considering integrating this library into our work as an option to synthesize a population (plug and play among others) and in doing so contributing to the codebase. Is it possible to put a standard license on the library like MIT or BSD?

**Comment by bstabler** [comment]
The license is in [setup.py](https://github.com/ActivitySim/populationsim/blob/master/setup.py#L15) and is [BSD-3](https://opensource.org/licenses/BSD-3-Clause).  Is that what you had in mind?

**Comment by josiekre** [comment]
Oh yes-- that works. `License.txt` has something different.

**Comment by josiekre** [comment]
I'll close this. 

I've seen a couple ways of making these match though: https://github.com/pandas-dev/pandas/blob/master/LICENSE puts BSD in the first line of the file. 

The Numpy library got Github UI to show BSD at the top when viewing their LICENSE. See their commit message on this: https://github.com/numpy/numpy/commit/a08fb60447be61b9136ba64947b79e987f696001.
