### ISSUE TITLE
repop-pop-pop feature - pipeline file is not updated

### ISSUE THREAD

**Issue by nsdhakar** [ActivitySim/populationsim#140]
A popsim repop run does not update the pipeline with updated population. The pipeline file is still the same as it started with.

**Comment by bstabler** [comment]
I talked with @nsdhakar and the use case here was to re-pop-pop-pop-.... (i.e. run it several times and accumulative results in the same database).  This use case was not part of the design and so I'm not surprised to hear it doesn't work.  This could be a feature to support in the future.
