### ISSUE TITLE
Adjust a third party synthetic population

### ISSUE THREAD

**Issue by inoruk94** [ActivitySim/populationsim#174]
Hello, 

I have at my disposal a third party synthetic population WITH trips already generated and associated with persons. 
However, the synthetic population is not exactly correct. 

Is there a way to clean and adjust this synthetic population and somehow keep the trips information for each persons ?

Maybe this could be achieved using the repop mode ?
I saw on the forum (issue  #135) that, for now, the creation of the seed synthetic population hdf5 datastore is mandatory. 
What are the steps to create such a seed ? How much time would that take ?

Or would it be possible to generate weights for every person which would help to adjust the synthetic population without having to generate new households and persons ?
Would this method be possible with the survey_weighting mode ?

Or maybe do you see other ways to adjust this synthetic population ?

Thank you for your answers !

**Comment by bettinardi** [comment]
It's not clear to me what parts of your existing population you want to adjust.  Could you add a little more detail on what you are hoping to change in your existing synthetic population?

**Comment by inoruk94** [comment]
I would like my population to match the governement' statistical data (I'm working in Belgium) for different parameters : the total number of persons per statistical zone, the distribution of persons per statistical zone by age, income, active/inactive, profession

These parameters are not correct for my current existing synthetic population

**Comment by binnympaul** [comment]
I concur with @bettinardi. The repop feature works only when you have an existing PopulationSim setup. You would probably need to start from scratch. You may use the existing syn pop as the seed but the existing weight may not be very useful as initial weights.

**Comment by Jxr99int2013** [comment]
We are using the Repop the first time since the PopulationSim's adoption in the Southern Oregon ABM in 2020. The example did work on its setup, but not the real application even though we are testing one MAZ (micro-analysis zone), the lowest zonal level. But the example was based on TAZ, the lowest zonal level. Still trying to figure out why not.

**Comment by bettinardi** [comment]
Sorry to leave this cold - I'm working to review outstanding issues - is this still a concern/issue?

**Comment by bettinardi** [comment]
I'm glad you were able to get to a workable solution.  Sorry the PopulationSim software was not useful to you in this case.
