### ISSUE TITLE
WGTP and PWGTP Calculations

### ISSUE THREAD

**Issue by dogaevren** [ActivitySim/populationsim#175]
We do not have detailed census data. As we understand, we need a detailed set for WGTP and PGWTP calculations. At this point, how should we calculate WGTP and PGWTP values in order to produce a synthetic population? What should be the necessary variables or similar things?

**Comment by bettinardi** [comment]
Do you have a household travel survey?  One of the anticipated seeds for the tool is a household travel survey.  If not - what detailed understanding of your populations characteristics (demographics) do you have available?

**Comment by dogaevren** [comment]
We have a household survey, and we already took some data for person seed such as car availability, age, hh size, driver license and etc. Yet, we could not find the way to calculate or estimate weight values for the person and household seed data. Thats why actually we are asking to help for calcculating PWGTP and WTGTP variables.

**Comment by bettinardi** [comment]
Ahhh...  I see now I didn't fully think through the issue you are up against.  Right, here in the US, census is used to determine the weights on our travel surveys.  Without some knowledge of the total population's size and demographics I'm not aware of a way to calculate weights.

If you do not have a data source that knows or approximates demographic information for the population of your region, I don't think you will have a method to develop weights.  In that case your, only option might be to assume that your travel survey perfectly represents your population (no over or under sampling), and in that case your weights would be the same for each record.  The weight for each record would be the total population for your region divided by the number of records in your survey.  So if you had a million people in your region and thousand people in your survey, the person weight would be 1,000 for each person.

**Comment by Jxr99int2013** [comment]
Are the census PWGTP and WTGTP specifically designed or targeted for each State, such as Oregon? I noted that the PWGTP in the Southern Oregon PopulationSim do not line up with the ACS or Census's PWGTP, but follow exactly the Oregon Households WGTP, which are different from the Oregon State PWGTP.

**Comment by bettinardi** [comment]
Sorry I left this question cold.  I'm no census expert, but I do think the household weights are different than the person weights when it comes to the US census products.  For your use I think they can be one in the same.  Does that help - is this still a question you are trying to resolve (again, sorry about the delay).

**Comment by Jxr99int2013** [comment]
No further comments. We are trying to work around the PopulationSim "repop" again for splitting 2 MAZs to 7 MAZ and 7 TAZs.
